### ISSUE TITLE
mac10.11.6 

### ISSUE THREAD

**Issue by chingsos** [Jermic/Android-Crack-Tool#1]
--------------------------------------------------------START---------------------------------------------------------
java -jar /shakaapktool.jar d -f /Users/mac/Downloads/walksee.apk -o /Users/mac/Downloads/walksee-O/
--------------------------------------------------------START---------------------------------------------------------

----------------------------------------------------------END----------------------------------------------------------

**Comment by Jermic** [comment]
It's depends on the apk
