### ISSUE TITLE
这两个版本 一直报 “已损坏”

### ISSUE THREAD

**Issue by oscar608** [Jermic/Android-Crack-Tool#10]
![image](https://cloud.githubusercontent.com/assets/10752360/25469311/12b1516a-2b4e-11e7-9f09-9948797de068.png)

**Comment by PanKoTlng** [comment]
https://www.google.com.tw/search?q=p731a10

**Comment by Jermic** [comment]
run
```shell
sudo spctl --master-disable
```
go to System Preferences > Security & Privacy > General > check Allow Anywhere
