### ISSUE TITLE
MacOS 10.12.5安装2.5.1版本出现问题

### ISSUE THREAD

**Issue by zeek007** [Jermic/Android-Crack-Tool#11]
Android Crack Tool.app”已损坏，打不开。 您应该将它移到废纸篓。
一直是报这个错误无法打开程序。。。

**Comment by Jermic** [comment]
https://github.com/Jermic/Android-Crack-Tool/issues/10  按照这个命令输入终端 然后 设置一下

**Comment by cxbsr** [comment]
同样遇到这个问题。。无解ing

**Comment by winzows** [comment]
打不开的是因为 你的电脑 限制了安装软件策略。。。。打开终端 终端就那个黑色的啦 输入sudo spctl --master-disable 按回车 回车就是你键盘上return那个按钮。输入你的密码 然后到系统偏好设置-安全与隐私里 把安装软件选择全部允许任何来源。。。。。。。。。。。。。。
