### ISSUE TITLE
Android Crack Tool”已损坏，打不开。 您应该推出磁盘映像。

### ISSUE THREAD

**Issue by tracyliu1** [Jermic/Android-Crack-Tool#14]
macOs 10.13.1

**Comment by kingang** [comment]
估计是没更新了，我也是这个问题

**Comment by 2666fff** [comment]
terminal  run
sudo spctl --master-disable

go to System Preferences > Security & Privacy > General > check Allow Anywhere

**Comment by winzows** [comment]
**打不开的是因为 你的电脑 限制了安装软件策略。。。。打开终端 终端就那个黑色的啦  输入sudo spctl --master-disable    按回车  回车就是你键盘上return那个按钮。输入你的密码  然后到系统偏好设置-安全与隐私里 把安装软件选择全部允许任何来源。。。。。。。。。。。。。。**

**Comment by MhuiHugh** [comment]
任何来源打开，还是提示已损坏。系统Mac 10.15.2，工具AndroidCrackTool.2.5.1.10-11

**Comment by hahaerle** [comment]
这个后面会修复吗  Mac 10.15.2
