### ISSUE TITLE
Android Crack Tool”已损坏，打不开。 您应该推出磁盘映像。

### ISSUE THREAD

**Issue by zp0605** [Jermic/Android-Crack-Tool#19]
打开的时候提示： "Android Crack Tool”已损坏，打不开。 您应该推出磁盘映像。

**Comment by ftc300** [comment]
sudo xattr -d com.apple.quarantine /Applications/AndroidCrackTool.app

**Comment by animus198656** [comment]
> sudo xattr -d com.apple.quarantine /Applications/AndroidCrackTool.app

正解
