### ISSUE TITLE
还在维护吗，还可以正常使用吗？

### ISSUE THREAD

**Issue by Maheaven** [Jermic/Android-Crack-Tool#22]
为什么我安装进入后  点击都没有反应

**Comment by SmallYuuu** [comment]
10.14系统没法用……

**Comment by Jermic** [comment]
![image](https://user-images.githubusercontent.com/5131979/48389222-79f33680-e737-11e8-86d2-e0e767a26ed4.png)
更新包可以自行替换apktool.jar
