### ISSUE TITLE
You have OS X 10.10.5. The application requires OS X 10.11 or later.

### ISSUE THREAD

**Issue by tanweijiu** [Jermic/Android-Crack-Tool#3]
1、You have OS X 10.10.5. The application requires OS X 10.11 or later.
2、 May  u  commit the code  so  may we run it by ourself..

**Comment by Jermic** [comment]
Try this ~ it's support for 10.9+
[AndroidCrackTool.2.5.10.9.dmg](https://github.com/Jermic/Android-Crack-Tool/releases/download/2.5/AndroidCrackTool.2.5.10.9.dmg)
