### ISSUE TITLE
os10.12.2 提示文件损坏

### ISSUE THREAD

**Issue by hyfink** [Jermic/Android-Crack-Tool#7]
github下载的AndroidCrackTool.2.5.1.10-9和AndroidCrackTool.2.5.1.10-11，安装完成后，打开时都提示文件损坏请移到废纸篓。

**Comment by Jermic** [comment]
系统设置 -> 安全与隐私 -> 基本设置 -> 勾选允许 Apps from anywhere

**Comment by hyfink** [comment]
10.12取消了这个选项。打开一个“来路不明”的APP时，会在那个界面临时出现一个允许打开的选项。但是打开这个应用并未提示。仅弹对话框提示文件已损坏。

**Comment by Jermic** [comment]
从百度盘下载试试呢

**Comment by hyfink** [comment]
也不行。

**Comment by Jermic** [comment]
我的也是10.12 就可以~ 你下载下来的东西有问题吧

**Comment by miaomi** [comment]
https://apple.stackexchange.com/questions/58050/damaged-and-cant-be-open-app-error-message
xattr -rc
